name: Admin Web CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'admin-web/**'
      - '.github/workflows/admin-web.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'admin-web/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install Dependencies
        run: cd admin-web && pnpm install
        
      - name: Run Lint
        run: cd admin-web && pnpm lint
        
      - name: Run Type Check
        run: cd admin-web && pnpm tsc --noEmit
        
  build-and-deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install Dependencies
        run: cd admin-web && pnpm install
        
      - name: Build
        run: cd admin-web && pnpm build
        env:
          VITE_API_BASE_URL: ${{ secrets.PROD_API_BASE_URL }}
          VITE_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          VITE_OPENAI_API_URL: ${{ secrets.OPENAI_API_URL }}
          VITE_DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          VITE_DEEPSEEK_API_URL: ${{ secrets.DEEPSEEK_API_URL }}
          
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/godin-lowcode
            git pull
            cd admin-web
            rm -rf /var/www/html/*
            cp -r dist/* /var/www/html/ 