name: Admin Server CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'admin-server/**'
      - '.github/workflows/admin-server.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'admin-server/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install Dependencies
        run: cd admin-server && pnpm install
        
      - name: Run Lint
        run: cd admin-server && pnpm lint
        
      - name: Run Tests
        run: cd admin-server && pnpm test
        env:
          MONGODB_URI: mongodb://localhost:27017/test
          REDIS_URL: redis://localhost:6379
          JWT_SECRET: test-secret
          
  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Install Dependencies
        run: cd admin-server && pnpm install
        
      - name: Build
        run: cd admin-server && pnpm build
        
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/godin-lowcode
            git pull
            cd admin-server
            pnpm install
            pnpm build
            pm2 restart admin-server 